[project]
name = "advent-of-code"
description = "This project holds my solutions to the Advent of Code."
version = "1.0.0"
requires-python = ">= 3.12"
dependencies = [
  "icecream"
]
authors = [
  { name = "Nick Quinn", email = "nickquinn3131@gmail.com" }
]
